{{- if .Values.features.external_database.enabled -}}

# Remove the database instance group.
- type: remove
  path: /instance_groups/name=database

# Remove the database variables.
- type: remove
  path: /variables/name=cf_mysql_mysql_admin_password
- type: remove
  path: /variables/name=cf_mysql_mysql_cluster_health_password
- type: remove
  path: /variables/name=cf_mysql_mysql_galera_healthcheck_endpoint_password
- type: remove
  path: /variables/name=cf_mysql_mysql_galera_healthcheck_password
- type: remove
  path: /variables/name=cf_mysql_proxy_api_password
- type: remove
  path: /variables/name=network_policy_database_password
- type: remove
  path: /variables/name=network_connectivity_database_password
- type: remove
  path: /variables/name=routing_api_database_password
- type: remove
  path: /variables/name=locket_database_password
- type: remove
  path: /variables/name=cc_database_password
- type: remove
  path: /variables/name=credhub_database_password
- type: remove
  path: /variables/name=diego_database_password
- type: remove
  path: /variables/name=uaa_database_password
- type: remove
  path: /variables/name=pxc_galera_ca
- type: remove
  path: /variables/name=pxc_server_ca
- type: remove
  path: /variables/name=galera_server_certificate
- type: remove
  path: /variables/name=mysql_server_certificate

# Remove database links.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/consumes?
  value: {database: nil}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/consumes?
  value: {database: nil}
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/consumes?
  value: {database: nil}
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/consumes?
  value: {database: nil}
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/consumes?
  value: {database: nil}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/consumes?
  value: {database: nil}
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/consumes?
  value: {database: nil}

# Replace database config for the jobs.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/db_scheme
  value: {{ .Values.features.external_database.type | quote }}
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/port
  value: {{ .Values.features.external_database.port }}
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/databases/tag=uaa/name
  value: {{ .Values.features.external_database.databases.uaa.name | quote }}
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/address?
  value: {{ .Values.features.external_database.host | quote }}
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/roles/name=uaa/password
  value: {{ .Values.features.external_database.databases.uaa.password | quote }}
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/roles/name=uaa/name
  value: {{ .Values.features.external_database.databases.uaa.username | quote }}
- type: remove
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa?/ca_certs
- type: remove
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/tls_enabled?

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/db_scheme
  value: &external_cc_database_scheme {{ .Values.features.external_database.type | quote }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/port
  value: &external_cc_database_port {{ .Values.features.external_database.port }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/databases/tag=cc/name
  value: &external_cc_database_name {{ .Values.features.external_database.databases.cc.name | quote }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/address?
  value: &external_cc_database_address {{ .Values.features.external_database.host | quote }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/roles/name=cloud_controller/password
  value: &external_cc_database_password {{ .Values.features.external_database.databases.cc.password | quote }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/roles/name=cloud_controller/name
  value: &external_cc_database_username {{ .Values.features.external_database.databases.cc.username | quote }}
- type: remove
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/ca_cert?

- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/db_scheme
  value: *external_cc_database_scheme
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/port
  value: *external_cc_database_port
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/databases/tag=cc/name
  value: *external_cc_database_name
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/address?
  value: *external_cc_database_address
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/roles/name=cloud_controller/password
  value: *external_cc_database_password
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/roles/name=cloud_controller/name
  value: *external_cc_database_username
- type: remove
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/ca_cert?

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/db_scheme
  value: *external_cc_database_scheme
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/port
  value: *external_cc_database_port
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/databases/tag=cc/name
  value: *external_cc_database_name
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/address?
  value: *external_cc_database_address
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/roles/name=cloud_controller/password
  value: *external_cc_database_password
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/roles/name=cloud_controller/name
  value: *external_cc_database_username
- type: remove
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/ca_cert?

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/db_scheme
  value: *external_cc_database_scheme
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/port
  value: *external_cc_database_port
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/databases/tag=cc/name
  value: *external_cc_database_name
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/address?
  value: *external_cc_database_address
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/roles/name=cloud_controller/password
  value: *external_cc_database_password
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/roles/name=cloud_controller/name
  value: *external_cc_database_username
- type: remove
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/ca_cert?

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_driver
  value: {{ .Values.features.external_database.type | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_port
  value: {{ .Values.features.external_database.port }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_schema
  value: {{ .Values.features.external_database.databases.bbs.name | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_host?
  value: {{ .Values.features.external_database.host | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_password
  value: {{ .Values.features.external_database.databases.bbs.password | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_username
  value: {{ .Values.features.external_database.databases.bbs.username | quote }}
- type: remove
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/ca_cert?
- type: remove
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/require_ssl?

- type: replace
  path: /instance_groups/name=routing-api/jobs/name=routing-api/properties/routing_api/sqldb/type
  value: {{ .Values.features.external_database.type | quote }}
- type: replace
  path: /instance_groups/name=routing-api/jobs/name=routing-api/properties/routing_api/sqldb/port
  value: {{ .Values.features.external_database.port }}
- type: replace
  path: /instance_groups/name=routing-api/jobs/name=routing-api/properties/routing_api/sqldb/schema
  value: {{ .Values.features.external_database.databases.routing_api.name | quote }}
- type: replace
  path: /instance_groups/name=routing-api/jobs/name=routing-api/properties/routing_api/sqldb/host?
  value: {{ .Values.features.external_database.host | quote }}
- type: replace
  path: /instance_groups/name=routing-api/jobs/name=routing-api/properties/routing_api/sqldb/password
  value: {{ .Values.features.external_database.databases.routing_api.password | quote }}
- type: replace
  path: /instance_groups/name=routing-api/jobs/name=routing-api/properties/routing_api/sqldb/username
  value: {{ .Values.features.external_database.databases.routing_api.username | quote }}
- type: remove
  path: /instance_groups/name=routing-api/jobs/name=routing-api/properties/routing_api/sqldb/ca_cert?

- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/type
  value: {{ .Values.features.external_database.type | quote }}
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/port
  value: {{ .Values.features.external_database.port }}
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/name
  value: {{ .Values.features.external_database.databases.policy_server.name | quote }}
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/host
  value: {{ .Values.features.external_database.host | quote }}
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/password
  value: {{ .Values.features.external_database.databases.policy_server.password | quote }}
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/username
  value: {{ .Values.features.external_database.databases.policy_server.username | quote }}
- type: remove
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/ca_cert?
- type: remove
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/require_ssl?

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/database/type
  value: {{ .Values.features.external_database.type | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/database/port
  value: {{ .Values.features.external_database.port }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/database/name
  value: {{ .Values.features.external_database.databases.silk_controller.name | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/database/host
  value: {{ .Values.features.external_database.host | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/database/password
  value: {{ .Values.features.external_database.databases.silk_controller.password | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/database/username
  value: {{ .Values.features.external_database.databases.silk_controller.username | quote }}
- type: remove
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/database/ca_cert?
- type: remove
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/database/require_ssl?

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/db_driver
  value: {{ .Values.features.external_database.type | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/db_port
  value: {{ .Values.features.external_database.port }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/db_schema
  value: {{ .Values.features.external_database.databases.locket.name | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/db_host?
  value: {{ .Values.features.external_database.host | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/db_password
  value: {{ .Values.features.external_database.databases.locket.password | quote }}
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/db_username
  value: {{ .Values.features.external_database.databases.locket.username | quote }}
- type: remove
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/ca_cert?
- type: remove
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/require_ssl?

- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/type
  value: {{ .Values.features.external_database.type | quote }}
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/port
  value: {{ .Values.features.external_database.port }}
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/database
  value: {{ .Values.features.external_database.databases.credhub.name | quote }}
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/host
  value: {{ .Values.features.external_database.host | quote }}
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/password
  value: {{ .Values.features.external_database.databases.credhub.password | quote }}
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/username
  value: {{ .Values.features.external_database.databases.credhub.username | quote }}
- type: remove
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/tls_ca?
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/require_tls?
  value: false

{{- else -}}

# Override the addresses for the jobs under the scheduler instance group.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/address?
  value: sql-db.service.cf.internal
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/address
  value: sql-db.service.cf.internal

# Configure the persistent disk in the way that cf-operator can provision.
- type: replace
  path: /instance_groups/name=database/persistent_disk?
  value: 20480 # 20GB
{{- if .Values.kube.storage_class }}
- type: replace
  path: /instance_groups/name=database/persistent_disk_type
  value: {{ .Values.kube.storage_class }}
{{- else }}
- type: remove
  path: /instance_groups/name=database/persistent_disk_type
{{- end }}

# Replace the jobs using the cf-mysql-release.
- type: replace
  path: /instance_groups/name=database/jobs
  value:
    - name: mysql
      release: cf-mysql
      properties:
        cf_mysql:
          mysql:
            enable_galera: false
            admin_password: "((cf_mysql_mysql_admin_password))"
            port: 3306
            binlog_enabled: false
            cluster_health:
              password: "((cf_mysql_mysql_cluster_health_password))"
            galera_healthcheck:
              db_password: "((cf_mysql_mysql_galera_healthcheck_password))"
              endpoint_username: galera_healthcheck
              endpoint_password: "((cf_mysql_mysql_galera_healthcheck_endpoint_password))"
            seeded_databases:
            - name: cloud_controller
              username: cloud_controller
              password: "((cc_database_password))"
            - name: credhub
              password: ((credhub_database_password))
              username: credhub
            - name: diego
              username: diego
              password: "((diego_database_password))"
            - name: network_connectivity
              username: network_connectivity
              password: "((network_connectivity_database_password))"
            - name: network_policy
              username: network_policy
              password: "((network_policy_database_password))"
            - name: routing-api
              username: routing-api
              password: "((routing_api_database_password))"
            - name: uaa
              username: uaa
              password: "((uaa_database_password))"
            - name: locket
              username: locket
              password: "((locket_database_password))"
            tls:
              ca_certificate: "((pxc_server_ca.certificate))"
              server_certificate: "((mysql_server_certificate.certificate))"
              server_key: "((mysql_server_certificate.private_key))"

# Add quarks properties. It adds the BPM configuration as cf-mysql-release lacks
# support for it upstream.
- type: replace
  path: /instance_groups/name=database/jobs/name=mysql/properties/quarks?
  value:
    ports:
    - name: mysql
      protocol: TCP
      internal: 3306
    run:
      healthcheck:
        mariadb:
          readiness:
            exec:
              command:
              - /var/vcap/packages/mariadb/bin/mysqladmin
              - --defaults-file=/var/vcap/jobs/mysql/config/mylogin.cnf
              - ping
          liveness:
            # Check for mysql, as we go through a bunch of control scripts
            # before the actual database server is run; ensure that all of that
            # is succeeding and we actually have a DB.
            exec:
              command: [pidof, mysqld]
    bpm:
      processes:
      - name: mariadb
        limits:
          open_files: 1048576
        persistent_disk: true
        executable: /bin/bash
        args:
          - -c
          - |-
            {{- .Files.Get "assets/scripts/jobs/mariadb/bpm_process.sh" | nindent 12 }}

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/database_*" }}
{{ $root.Files.Get $path }}
{{- end }}

{{- end }}
