{{- if .Values.settings.router.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-router-tls-ca" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
type: Opaque
stringData:
{{- with $tls := .Values.settings.router.tls }}
  ca: |
    {{- (default "" $tls.ca) | nindent 4 }}
{{- end }}
{{- end }}
