---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ops-sizing
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: operations
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
data:
  ops: |
    {{- $instance_groups := list }}

    {{- /* Core instance groups that always exist */}}
    {{- $instance_groups = append $instance_groups "adapter" }}
    {{- $instance_groups = append $instance_groups "api" }}
    {{- $instance_groups = append $instance_groups "auctioneer" }}
    {{- $instance_groups = append $instance_groups "cc-worker" }}
    {{- $instance_groups = append $instance_groups "diego-api" }}
    {{- $instance_groups = append $instance_groups "log-api" }}
    {{- $instance_groups = append $instance_groups "nats" }}
    {{- $instance_groups = append $instance_groups "router" }}
    {{- $instance_groups = append $instance_groups "routing-api" }}
    {{- $instance_groups = append $instance_groups "scheduler" }}
    {{- $instance_groups = append $instance_groups "uaa" }}
    {{- $instance_groups = append $instance_groups "tcp-router" }}

    {{- /* Autoscaler-only instance groups */}}
    {{- if .Values.features.autoscaler.enabled }}
    {{- $instance_groups = append $instance_groups "asapi" }}
    {{- $instance_groups = append $instance_groups "asactors" }}
    {{- $instance_groups = append $instance_groups "asmetrics" }}
    {{- $instance_groups = append $instance_groups "asnozzle" }}
    {{- end }}{{/* if autoscaler */}}

    {{- /* CredHub */}}
    {{- if .Values.features.credhub.enabled }}
    {{- $instance_groups = append $instance_groups "credhub" }}
    {{- end }}{{/* if credhub */}}

    {{- /* Instances groups where existance depends on whether Eirini is enabled */}}
    {{- if and .Values.features.eirini.enabled (not .Values.features.eirini.use_helm_release) }}
    {{- $instance_groups = append $instance_groups "bits" }}
    {{- $instance_groups = append $instance_groups "eirini" }}
    {{- else }}
    {{- $instance_groups = append $instance_groups "diego-cell" }}
    {{- end }}{{/* if eirini */}}

    # Temporarily fixes https://github.com/SUSE/kubecf/issues/241.
    # TODO: properly investigate and fix log-cache.
    - type: replace
      path: /instance_groups/name=doppler/instances
      value: 1

{{- range $instance_group := $instance_groups }}
{{- if index (snakecase $instance_group | index $.Values.sizing) "instances" | kindIs "invalid" | not }}
    - type: replace
      path: /instance_groups/name={{ $instance_group }}/instances
      value: {{ index (snakecase $instance_group | index $.Values.sizing) "instances" }}
{{- else if not $.Values.high_availability }}
    - type: replace
      path: /instance_groups/name={{ $instance_group }}/instances
      value: 1
{{- end }}{{/* if */}}
{{- end }}{{/* range $instance_group */}}
